apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    name: demo-deployment
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      name: demo-pod
  template:
    metadata:
      name: demo-pod
      labels:
        name: demo-pod
    spec:
      containers:
      - name: demo-container
        image: nginx:1.17
        ports:
        - containerPort: 80